Драфт схемы БД с патчем
masterway/masterway pull request #5
Opened 2017-02-04 16:18 UTC by Artem-7

Первый вариант схемы (тот, что готовил к презентации в пятницу). На текущий момент не учитывает требование хранить общие для маршрута настройки отдельно от варианта

2017-02-07 14:42 UTC, rnljul reviewed
Ознакомился со структурой.

2017-02-07 14:45 UTC, rnljul requested changes
надо кодировку править

2017-02-07 16:14 UTC, chameleon82 approved these changes
С кодировкой беда. Давайте в UTF8 все вести?

2017-02-07 16:16 UTC, chameleon82 commented
Рома, ты можешь заапрувить?

2017-02-07 16:28 UTC, rnljul commented
Я не вижу кнопку APPROVE, и у меня нет прав на запись, значит сливать тоже не могу.
На счет кодировки - давайте UTF-8.

2017-02-07 16:29 UTC, rnljul approved these changes

2017-02-07 16:30 UTC, rnljul commented
С аппрувом разобрался.

2017-02-07 17:43 UTC, Artem-7 commented
Добавил в реквест коммит, исправляющий кодировку

2017-02-12 07:00 UTC, rnljul reviewed
Давайте заменим префикс MV на RS (route system)

2017-02-12 16:19 UTC, rnljul approved these changes

2017-02-12 16:20 UTC, rnljul commented
А у кого права на запись есть? Слейте реквест!

2017-02-13 11:20 UTC, merged